---
title: "COVID State Web Scraping"
output: html_document
---

```{r, message = FALSE, warning = FALSE }
library(tidyverse)
library(pdftools)
library(rvest)
library(lubridate)
library(readxl)

old_cols = c(
    "total",
    "age_0_19", 
    "age_20_29", 
    "age_30_39", 
    "age_40_49",
    "age_50_59", 
    "age_60_69", 
    "age_70_79", 
    "age_80+", 
    "age_unk",
    "sex_male", 
    "sex_female", 
    "sex_unk",
    "ethnicity_hispanic", 
    "ethnicity_non_hispanic",
    "ethnicity_unk",
    "race_white", 
    "race_AfrA",
    "race_NatA",
    "race_asian", 
    "race_other",
    "race_multi", 
    "race_unk")

# Helper functions for data cleaning
skeleton_col = function(subdivs) {
  # Need to make a named vector to make it easier to insert data
  # in a cel-wise fashion
  
  # subdivs should contain all of the relevant information that
  # a state provides on their websitE
  
  skeleton = vector(mode = "list", length = length(subdivs))
  names(skeleton) = subdivs
  return(skeleton)
}

skeleton_table = function(subdivs) {
  # Create a table of blanks using named vectors
  # Easy insert of data
  skeleton = list(
    "data" = names(skeleton_col(subdivs)),
    "tested" = skeleton_col(subdivs),
    "cases" = skeleton_col(subdivs),
    "negatives" = skeleton_col(subdivs),
    "recovered" = skeleton_col(subdivs),
    "deaths" = skeleton_col(subdivs),
    "hospitalized" = skeleton_col(subdivs))
  return(skeleton)
}

example = skeleton_table(old_cols)
example_tibble = as_tibble(example)
```

# Nevada

- Doesn't work out because data is hidden under the Microsoft BI dashboard and the pdfs that hold the data show images, not text

```{r}
nevada = read_html("https://nvhealthresponse.nv.gov/") %>% 
    html_nodes(".js-side-cta") %>% 
    html_nodes(".split-content-section") %>% 
    html_nodes(".split-content-section__container") %>% 
    html_nodes(".content-intro") %>% 
    html_nodes("iframe") %>% 
    xml_attrs() %>% 
    .[[1]] %>% 
    .[1] %>% # This returns another html that comes from the iframe
    read_html() %>% 
    html_nodes("#pbiAppPlaceHolder")
  
  return(nevada)
```

# Iowa

```{r}
# Need to access the data through daily pdfs
# Get pdfs from Tableau download: https://coronavirus.iowa.gov/#CurrentStatus

# Pain point: must redownload pdf from Tableau table every day, 
# then put it in pdfs folder
# Download the "Current Status" and "Demographics" sheets as pdf 

now = Sys.time() %>% as_date() %>% as.character()
date_for_url = paste0(str_sub(now, 6,7), 
                      str_sub(now, 9, 10), 
                      str_sub(now, 1,4))

iowa = pdf_text(paste0("../pdfs/IowaCOVID19_", date_for_url, ".pdf"))

extract_iowa_data = function(pdf_data) {
  total_page = pdf_data[1] %>% str_split(., "\n") %>% .[[1]]
  demographics_page = pdf_data[2] %>% str_split(., "\n") %>% .[[1]]
  
  total_confirmed_cases = total_page[35] %>% 
    str_split(" ") %>% .[[1]] %>% head(1) %>% 
    str_replace(., ",", "") %>% as.numeric()
  
  total_deaths = total_page[35] %>% 
    str_split(" ") %>% .[[1]] %>% tail(1) %>% 
    str_replace(., ",", "") %>% as.numeric()
  
  total_people_tested = total_page[37] %>% 
    str_split(" ") %>% .[[1]] %>% head(1) %>% 
    str_replace(., ",", "") %>% as.numeric()
  
  total_cases_recovered = total_page[37] %>% 
    str_split(" ") %>% .[[1]] %>% tail(1) %>% 
    str_replace(., ",", "") %>% as.numeric()
  
  
  return(list(
    total_confirmed_cases = total_confirmed_cases,
    total_deaths = total_deaths,
    total_people_tested = total_people_tested,
    total_cases_recovered = total_cases_recovered,
    demographic_string = demographic_page
  ))
}


extract_iowa_data(iowa)
```

# Delaware

```{r}
delaware = read_html("https://myhealthycommunity.dhss.delaware.gov/locations/state")
```

# Oklahoma

```{r}
extract_oklahoma_data = function() {
  data_url = "https://storage.googleapis.com/ok-covid-gcs-public-download/covid19_cases_summary.pdf"
  
  oklahoma = pdf_text(data_url) %>% 
    str_split(., "\n") %>% .[[1]] %>% 
    map(., str_squish)
  
  cases = oklahoma %>% .[[3]] %>% 
    str_split(., " ", simplify = TRUE) %>% 
    .[1, 5] %>% 
    str_replace(., ",", "") %>% as.numeric()
    
  deaths = oklahoma %>% .[[3]] %>% 
    str_split(., " ", simplify = TRUE) %>% 
    .[1, 6] %>% 
    str_replace(., ",", "") %>% as.numeric()
  
  recovered = oklahoma %>% .[[3]] %>% 
    str_split(., " ", simplify = TRUE) %>% 
    .[1, 7] %>% 
    str_replace(., ",", "") %>% as.numeric()
  
  # WARNING: super fragile coding follows
  # Makes some big assumptions on where numbers are placed
  # based on position, assumes these indices wont change much
  
  white_pct = oklahoma %>% .[[22]] %>% 
    str_split(., " ", simplify = TRUE) %>% .[1, 2] %>% 
    str_replace(., "%", "") %>% as.numeric() / 100
  
  unknown_race_pct = oklahoma %>% .[[25]] %>% 
    str_replace(., "%", "") %>% as.numeric()
  
  native_american_pct = oklahoma %>% .[[31]] %>% 
    str_split(., " ", simplify = TRUE) %>% .[1, 1] %>% 
    str_replace(., "%", "") %>% as.numeric() / 100

  multiple_race_pct = oklahoma %>% .[[42]] %>% 
    str_replace(., "%", "") %>% as.numeric() / 100
  
  asian_pct = oklahoma %>% .[[47]] %>% 
    str_replace(., "%", "") %>% as.numeric() / 100  
  
  african_american_pct = oklahoma %>% .[[38]] %>% 
    str_replace(., "%", "") %>% as.numeric() / 100
  
  between_0_and_4_pct = oklahoma %>% .[[39]] %>% 
    str_split(., " ", simplify = TRUE) %>% .[1, 2] %>% 
    str_replace(., "%", "") %>% as.numeric() / 100
  
  between_5_and_17_pct = oklahoma %>% .[[37]] %>% 
    str_split(., " ", simplify = TRUE) %>% .[1, 2] %>% 
    str_replace(., "%", "") %>% as.numeric() / 100  

  between_18_and_35_pct = oklahoma %>% .[[33]] %>% 
    str_split(., " ", simplify = TRUE) %>% .[1, 4] %>% 
    str_replace(., "%", "") %>% as.numeric() / 100
  
  between_36_and_49_pct = oklahoma %>% .[[35]] %>% 
    str_split(., " ", simplify = TRUE) %>% .[1, 2] %>% 
    str_replace(., "%", "") %>% as.numeric() / 100  

  between_50_and_64_pct = oklahoma %>% .[[32]] %>% 
    str_split(., " ", simplify = TRUE) %>% .[1, 2] %>% 
    str_replace(., "%", "") %>% as.numeric() / 100
  
  older_than_65_pct = oklahoma %>% .[[30]] %>% 
    str_split(., " ", simplify = TRUE) %>% .[1, 2] %>% 
    str_replace(., "%", "") %>% as.numeric() / 100   
   
  unknown_age_pct = oklahoma %>% .[[41]] %>% 
    str_split(., " ", simplify = TRUE) %>% .[1, 3] %>% 
    str_replace(., "%", "") %>% as.numeric() / 100
    
  return(list(
    cases = cases,
    deaths = deaths,
    recovered = recovered,
    white_cases = floor(cases * white_pct),
    unknown_race_cases = floor(cases * unknown_race_pct),
    african_american_cases = floor(cases * african_american_pct),
    native_american_cases = floor(cases * native_american_pct),
    multiple_race_cases = floor(cases * multiple_race_pct),
    asian_cases = floor(cases * asian_pct),
    african_american_cases = floor(cases * african_american_pct),
    between_0_and_4_cases = floor(cases * between_0_and_4_pct),
    between_5_and_17_cases = floor(cases * between_5_and_17_pct),
    between_18_and_35_cases = floor(cases * between_18_and_35_pct),
    between_36_and_49_cases = floor(cases * between_36_and_49_pct),
    between_50_and_64_cases = floor(cases * between_50_and_64_pct),
    older_than_65_cases = floor(cases * older_than_65_pct),
    unknown_age_cases = floor(cases * unknown_age_pct)
  ))
}

oklahoma = extract_oklahoma_data()
oklahoma
```

# Arizona

```{r}
extract_arizona_data = function() {
  url = "https://www.azdhs.gov/preparedness/epidemiology-disease-control/infectious-disease-epidemiology/covid-19/dashboards/index.php"
  # arizona = read_html()
  arizona = htmlParse(GET(url, user_agent("Mozilla")))
  return(arizona)
}

arizona = extract_arizona_data()
```

# Mississippi

```{r}
extract_mississippi_data = function() {
  
  # Extract pdf locations from the site to account for updates
  site_url = "https://msdh.ms.gov/msdhsite/_static/14,0,420.html"
  html = read_html(site_url) %>% 
    html_nodes("body") %>% 
    html_nodes("#pageContainer") %>% 
    html_nodes("#pageContent") %>% 
    html_nodes("#article") %>% 
    html_nodes(".msdh") %>% 
    html_nodes("ul") %>% .[[7]]
  
  cases_path = html %>% 
    xml_child(., 1) %>% 
    html_nodes("a") %>% 
    xml_attrs() %>% .[[1]]
  
  death_path = html %>% 
    xml_child(., 2) %>% 
    html_nodes("a") %>% 
    xml_attrs() %>% .[[1]]
  
  url = paste0("https://msdh.ms.gov/msdhsite/_static/", cases_path)
  deaths_url = paste0("https://msdh.ms.gov/msdhsite/_static/", death_path)
  
  
  
  # Table is by county, just need to look at the last row
  mississippi = pdf_text(url) %>% .[2] %>% 
    str_split(., "\n") %>% .[[1]] %>% .[17] %>% # Last row
    str_squish() %>%
    str_split(., " ") %>%  .[[1]] %>% .[-1] %>% # Removing "Total" string
    as.numeric()

  deaths = pdf_text(deaths_url) %>% .[2] %>% 
    str_split(., "\n") %>% .[[1]] %>% .[17] %>% # Last row
    str_squish() %>%
    str_split(., " ") %>%  .[[1]] %>% .[-1] %>% # Removing "Total" string
    as.numeric()
  
  return(list(
    cases = mississippi[1],
    deaths = deaths[1],
    white_cases = mississippi[3] + mississippi[9] + mississippi[15],
    unknown_race_cases = mississippi[7] + mississippi[13] + mississippi[19],
    native_american_cases = mississippi[4] + mississippi[10] + mississippi[16],
    african_american_cases = mississippi[2] + mississippi[8] + mississippi[14],
    asian_cases = mississippi[5] + mississippi[11] + mississippi[17],
    other_race_cases = mississippi[6] + mississippi[12] + mississippi[18],
    white_deaths = deaths[3] + deaths[9] + deaths[15],
    unknown_race_deaths = deaths[7] + deaths[13] + deaths[19],
    native_american_deaths = deaths[4] + deaths[10] + deaths[16],
    african_american_deaths = deaths[2] + deaths[8] + deaths[14],
    asian_deaths = deaths[5] + deaths[11] + deaths[17],
    other_race_deaths = deaths[6] + deaths[12] + deaths[18]
  ))
}

mississippi = extract_mississippi_data()
mississippi
```

# Florida

```{r}
extract_florida_data = function(pdf_url) {
  # Get pdf from: https://www.floridadisaster.org/covid19/covid-19-data-reports/
  
  data = pdf_text(pdf_url)
  
  demographic_data = data %>% .[3] %>% 
    str_split(., "\n") %>% .[[1]] %>% 
    str_squish()
  
  # Initialize skeleton
  skeleton = skeleton_table()
  
  tested = data %>% .[1] %>% 
    str_split(., "\n") %>% .[[1]] %>% 
    str_squish() %>% .[[22]] %>% 
    str_split(., " ", simplify = TRUE) %>% .[1, 3] %>% 
    str_replace(., ",", "") %>% as.numeric()
  
  negatives = data %>% .[1] %>% 
    str_split(., "\n") %>% .[[1]] %>% 
    str_squish() %>% .[[25]] %>% 
    str_split(., " ", simplify = TRUE) %>% .[1, 2] %>% 
    str_replace(., ",", "") %>% as.numeric()
  
  cases = demographic_data %>% .[16] %>% 
    str_split(., " ", simplify = TRUE) %>% .[1, 2] %>% 
    str_replace(., ",", "") %>% as.numeric()
  
  deaths = demographic_data %>% .[16] %>% 
    str_split(., " ", simplify = TRUE) %>% .[1, 4] %>% 
    str_replace(., ",", "") %>% as.numeric()
  
  # All of the following information applies to cases only
  males = demographic_data %>% .[5] %>% 
    str_split(., " ", simplify = TRUE) %>%  .[1, 10] %>% 
    str_replace(., ",", "") %>% as.numeric()
  
  # Age divisions don't match up against what I currently have
  between_0_and_4 = demographic_data %>% .[5] %>% 
    str_split(., " ", simplify = TRUE) %>%  .[1, 3] %>% 
    str_replace(., ",", "") %>% as.numeric()
  
  between_5_and_14 = demographic_data %>% .[6] %>% 
    str_split(., " ", simplify = TRUE) %>%  .[1, 3] %>% 
    str_replace(., ",", "") %>% as.numeric()
  
  between_15_and_24 = demographic_data %>% .[7] %>% 
    str_split(., " ", simplify = TRUE) %>%  .[1, 3] %>% 
    str_replace(., ",", "") %>% as.numeric()
  
  between_25_and_34 = demographic_data %>% .[8] %>% 
    str_split(., " ", simplify = TRUE) %>%  .[1, 3] %>% 
    str_replace(., ",", "") %>% as.numeric()
  
  between_35_and_44 = demographic_data %>% .[9] %>% 
    str_split(., " ", simplify = TRUE) %>%  .[1, 3] %>% 
    str_replace(., ",", "") %>% as.numeric()
  
  between_45_and_54 = demographic_data %>% .[10] %>% 
    str_split(., " ", simplify = TRUE) %>%  .[1, 3] %>% 
    str_replace(., ",", "") %>% as.numeric()
  
  between_55_and_64 = demographic_data %>% .[11] %>% 
    str_split(., " ", simplify = TRUE) %>%  .[1, 3] %>% 
    str_replace(., ",", "") %>% as.numeric()
  
  between_65_and_74 = demographic_data %>% .[12] %>% 
    str_split(., " ", simplify = TRUE) %>%  .[1, 3] %>% 
    str_replace(., ",", "") %>% as.numeric()
  
  between_75_and_84 = demographic_data %>% .[13] %>% 
    str_split(., " ", simplify = TRUE) %>%  .[1, 3] %>% 
    str_replace(., ",", "") %>% as.numeric()
  
  older_than_85 = demographic_data %>% .[14] %>% 
    str_split(., " ", simplify = TRUE) %>%  .[1, 3] %>% 
    str_replace(., ",", "") %>% as.numeric()
  
  unknown_age = demographic_data %>% .[15] %>% 
    str_split(., " ", simplify = TRUE) %>%  .[1, 2] %>% 
    str_replace(., ",", "") %>% as.numeric()
  
  hispanic = demographic_data %>% .[18] %>% 
    str_split(., " ", simplify = TRUE) %>%  .[1, 2] %>% 
    str_replace(., ",", "") %>% as.numeric()
  
  non_hispanic = demographic_data %>% .[19] %>% 
    str_split(., " ", simplify = TRUE) %>%  .[1, 2] %>% 
    str_replace(., ",", "") %>% as.numeric()
  
  unknown_race = demographic_data %>% .[20] %>% 
    str_split(., " ", simplify = TRUE) %>%  .[1, 2] %>% 
    str_replace(., ",", "") %>% as.numeric()
  
  hispanic_death = demographic_data %>% .[18] %>% 
    str_split(., " ", simplify = TRUE) %>%  .[1, 6] %>% 
    str_replace(., ",", "") %>% as.numeric()
  
  non_hispanic_death = demographic_data %>% .[19] %>% 
    str_split(., " ", simplify = TRUE) %>%  .[1, 6] %>% 
    str_replace(., ",", "") %>% as.numeric()
  
  unknown_race_death = demographic_data %>% .[20] %>% 
    str_split(., " ", simplify = TRUE) %>%  .[1, 6] %>% 
    str_replace(., ",", "") %>% as.numeric()
  
  white = demographic_data %>% .[23] %>% 
    str_split(., " ", simplify = TRUE) %>%  .[1, 2] %>% 
    str_replace(., ",", "") %>% as.numeric()
  
  black = demographic_data %>% .[27] %>% 
    str_split(., " ", simplify = TRUE) %>%  .[1, 2] %>% 
    str_replace(., ",", "") %>% as.numeric()
  
  other_ethnicity = demographic_data %>% .[31] %>% 
    str_split(., " ", simplify = TRUE) %>%  .[1, 2] %>% 
    str_replace(., ",", "") %>% as.numeric()
  
  unknown_ethnicity = demographic_data %>% .[35] %>% 
    str_split(., " ", simplify = TRUE) %>%  .[1, 3] %>% 
    str_replace(., ",", "") %>% as.numeric()
  
  white_death = demographic_data %>% .[23] %>% 
    str_split(., " ", simplify = TRUE) %>%  .[1, 6] %>% 
    str_replace(., ",", "") %>% as.numeric()
  
  black_death = demographic_data %>% .[27] %>% 
    str_split(., " ", simplify = TRUE) %>%  .[1, 6] %>% 
    str_replace(., ",", "") %>% as.numeric()
  
  other_ethnicity_death = demographic_data %>% .[31] %>% 
    str_split(., " ", simplify = TRUE) %>%  .[1, 6] %>% 
    str_replace(., ",", "") %>% as.numeric()
  
  unknown_ethnicity_death = demographic_data %>% .[35] %>% 
    str_split(., " ", simplify = TRUE) %>%  .[1, 7] %>% 
    str_replace(., ",", "") %>% as.numeric()

  # Log all of the information
  skeleton[["tested"]][["total"]] = tested
  skeleton[["negatives"]][["total"]] = negatives
  
  skeleton[["cases"]][["total"]] = cases
  skeleton[["cases"]][["sex_male"]] = males
  skeleton[["cases"]][["sex_female"]] = cases - males
  skeleton[["cases"]][["age_0_19"]] = between_0_and_4 + 
    between_5_and_14 + between_15_and_24 / 2
  skeleton[["cases"]][["age_20_29"]] = (between_15_and_24 / 2) + 
    (between_25_and_34 / 2)
  skeleton[["cases"]][["age_30_39"]] = (between_25_and_34 / 2) +
    (between_35_and_44 / 2)
  skeleton[["cases"]][["age_40_49"]] = (between_35_and_44 / 2) + 
    (between_45_and_54 / 2) 
  skeleton[["cases"]][["age_70_79"]] = (between_75_and_84 / 2) + 
    (between_65_and_74 / 2)
  skeleton[["cases"]][["age_50_59"]] = (between_55_and_64 / 2) + 
    (between_45_and_54 / 2)
  skeleton[["cases"]][["age_60_69"]] = (between_55_and_64 / 2) + 
    (between_65_and_74 / 2)
  skeleton[["cases"]][["age_80+"]] = (between_75_and_84 / 2) +
    older_than_85
  skeleton[["cases"]][["age_unk"]] = unknown_age
  skeleton[["cases"]][["ethnicity_hispanic"]] = hispanic
  skeleton[["cases"]][["ethnicity_non_hispanic"]] = non_hispanic
  skeleton[["cases"]][["ethnicity_unk"]] = unknown_race
  skeleton[["cases"]][["race_white"]] = white
  skeleton[["cases"]][["race_AfrA"]] = black
  skeleton[["cases"]][["race_other"]] = other_ethnicity
  skeleton[["cases"]][["race_unk"]] = unknown_ethnicity
  
  skeleton[["deaths"]][["total"]] = deaths
  skeleton[["deaths"]][["ethnicity_hispanic"]] = hispanic_death
  skeleton[["deaths"]][["ethnicity_non_hispanic"]] = non_hispanic_death
  skeleton[["deaths"]][["ethnicity_unk"]] = unknown_race_death
  skeleton[["deaths"]][["race_white"]] = white_death
  skeleton[["deaths"]][["race_AfrA"]] = black_death
  skeleton[["deaths"]][["race_other"]] = other_ethnicity_death
  skeleton[["deaths"]][["race_unk"]] = unknown_ethnicity_death
  
  return(list(
    data = as_tibble(skeleton),
    comments = list(
      "Age divisions don't match up to standard",
      "Halved split divisions here"
    )
  ))
  
}
florida = get_florida("https://www.floridadisaster.org/globalassets/covid19/dailies/covid-19-data---daily-report-2020-05-07-0956.pdf")
```

# Tennessee

```{r}
get_tennessee = function(date) {
  
  # Get download the datasets from the Tennessee site
  # https://www.tn.gov/health/cedep/ncov/data/downloadable-datasets.html
  age_temp = tempfile(fileext = ".xlsx")
  case_temp = tempfile(fileext = ".xlsx")
  demo_temp = tempfile(fileext = ".xlsx")
  
  age_url = "https://www.tn.gov/content/dam/tn/health/documents/cedep/novel-coronavirus/datasets/Public-Dataset-Age.xlsx"
  case_url = "https://www.tn.gov/content/dam/tn/health/documents/cedep/novel-coronavirus/datasets/Public-Dataset-Daily-Case-Info.xlsx"
  demo_url = "https://www.tn.gov/content/dam/tn/health/documents/cedep/novel-coronavirus/datasets/Public-Dataset-RaceEthSex.xlsx"
  
  download.file(age_url, destfile = age_temp, mode = 'wb')
  download.file(case_url, destfile = case_temp, mode = 'wb')
  download.file(demo_url, destfile = demo_temp, mode = 'wb')
  
  age_data = read_excel(age_temp, sheet = 1) %>% 
    filter(DATE == as_date(date))
  case_data = read_excel(case_temp, sheet = 1) %>% 
    filter(DATE == as_date(date))
  demo_data = read_excel(demo_temp, sheet = 1) %>% 
    filter(Date == as_date(date))
  
  skeleton = skeleton_table()
  
  tests = case_data %>% pull(TOTAL_TESTS)
  cases = case_data %>% pull(TOTAL_CASES)
  negatives = case_data %>% pull(NEG_TESTS)
  deaths = case_data %>% pull(TOTAL_DEATHS)
  recovered = case_data %>% pull(TOTAL_RECOVERED)
  
  ar_cases = age_data %>% pull(AR_CASECOUNT)
  ar_deaths = age_data %>% pull(AR_TOTALDEATHS)
  
  race_cases = demo_data %>% filter(Category == "RACE")
  ethnicity_cases = demo_data %>% filter(Category == "ETHNICITY") 
  sex_cases = demo_data %>% filter(Category == "SEX")
  
  race_deaths = demo_data %>% filter(Category == "RACE")
  ethnicity_deaths = demo_data %>% filter(Category == "ETHNICITY")
  sex_deaths = demo_data %>% filter(Category == "SEX")
  
  # Log all the data from the Excel sheet
  skeleton[["tested"]][["total"]] = tests
  
  skeleton[["cases"]][["total"]] = cases
  skeleton[["cases"]][["age_0_19"]] = ar_cases[1] + ar_cases[2]
  skeleton[["cases"]][["age_20_29"]] = ar_cases[3]
  skeleton[["cases"]][["age_30_39"]] = ar_cases[4]
  skeleton[["cases"]][["age_40_49"]] = ar_cases[5]
  skeleton[["cases"]][["age_50_59"]] = ar_cases[6]
  skeleton[["cases"]][["age_60_69"]] = ar_cases[7]
  skeleton[["cases"]][["age_70_79"]] = ar_cases[8]
  skeleton[["cases"]][["age_80+"]] = ar_cases[9]
  skeleton[["cases"]][["age_unk"]] = ar_cases[10]
  skeleton[["cases"]][["sex_male"]] = sex_cases %>% 
    filter(Cat_Detail == "Male") %>% pull(Cat_CaseCount) 
  skeleton[["cases"]][["sex_female"]] = sex_cases %>% 
    filter(Cat_Detail == "Female") %>% pull(Cat_CaseCount) 
  skeleton[["cases"]][["sex_unk"]] = sex_cases %>% 
    filter(Cat_Detail == "Pending") %>% pull(Cat_CaseCount) 
  skeleton[["cases"]][["race_white"]] = race_cases %>% 
    filter(Cat_Detail == "White") %>% pull(Cat_CaseCount) 
  skeleton[["cases"]][["race_AfrA"]] = race_cases %>% 
    filter(Cat_Detail == "Black or African American") %>% pull(Cat_CaseCount) 
  skeleton[["cases"]][["race_other"]] = race_cases %>% 
    filter(Cat_Detail == "Other/Multiracial") %>% pull(Cat_CaseCount)
  skeleton[["cases"]][["race_asian"]] = race_cases %>% 
    filter(Cat_Detail == "Asian") %>% pull(Cat_CaseCount) 
  skeleton[["cases"]][["race_unk"]] = race_cases %>% 
    filter(Cat_Detail == "Pending") %>% pull(Cat_CaseCount) 
  skeleton[["cases"]][["ethnicity_hispanic"]] = ethnicity_cases %>% 
    filter(Cat_Detail == "Hispanic") %>% pull(Cat_CaseCount)
  skeleton[["cases"]][["ethnicity_non_hispanic"]] = ethnicity_cases %>% 
    filter(Cat_Detail == "Not Hispanic or Latino") %>% pull(Cat_CaseCount)
  skeleton[["cases"]][["ethnicity_unk"]] = ethnicity_cases %>% 
    filter(Cat_Detail == "Pending") %>% pull(Cat_CaseCount)
  
  skeleton[["negatives"]][["total"]] = negatives
  
  skeleton[["deaths"]][["total"]] = deaths
  skeleton[["deaths"]][["age_20_29"]] = ar_deaths[3]
  skeleton[["deaths"]][["age_30_39"]] = ar_deaths[4]
  skeleton[["deaths"]][["age_40_49"]] = ar_deaths[5]
  skeleton[["deaths"]][["age_50_59"]] = ar_deaths[6]
  skeleton[["deaths"]][["age_60_69"]] = ar_deaths[7]
  skeleton[["deaths"]][["age_70_79"]] = ar_deaths[8]
  skeleton[["deaths"]][["age_80+"]] = ar_deaths[9]
  skeleton[["deaths"]][["age_unk"]] = ar_deaths[10]
  skeleton[["deaths"]][["race_white"]] = race_deaths %>% 
    filter(Cat_Detail == "White") %>% pull(CAT_DEATHCOUNT) 
  skeleton[["deaths"]][["race_AfrA"]] = race_deaths %>% 
    filter(Cat_Detail == "Black or African American") %>% pull(CAT_DEATHCOUNT) 
  skeleton[["deaths"]][["race_other"]] = race_deaths %>% 
    filter(Cat_Detail == "Other/Multiracial") %>% pull(CAT_DEATHCOUNT)
  skeleton[["deaths"]][["race_asian"]] = race_deaths %>% 
    filter(Cat_Detail == "Asian") %>% pull(CAT_DEATHCOUNT) 
  skeleton[["deaths"]][["race_unk"]] = race_deaths %>% 
    filter(Cat_Detail == "Pending") %>% pull(CAT_DEATHCOUNT) 
  skeleton[["deaths"]][["ethnicity_hispanic"]] = ethnicity_deaths %>% 
    filter(Cat_Detail == "Hispanic") %>% pull(CAT_DEATHCOUNT)
  skeleton[["deaths"]][["ethnicity_non_hispanic"]] = ethnicity_deaths %>% 
    filter(Cat_Detail == "Not Hispanic or Latino") %>% pull(CAT_DEATHCOUNT)
  skeleton[["deaths"]][["ethnicity_unk"]] = ethnicity_deaths %>% 
    filter(Cat_Detail == "Pending") %>% pull(CAT_DEATHCOUNT)
  
  skeleton[["recovered"]][["total"]] = recovered
  
  return(list(
    data = as_tibble(skeleton),
    comments = list(
      "Age ranges are slightly off here"
    )
    ))
}
tennessee = get_tennessee("2020/05/07")
```

# North Carolina

```{r}
get_north_carolina = function() {
  skeleton = skeleton_table()
  url = "https://www.ncdhhs.gov/divisions/public-health/covid19/covid-19-nc-case-count#by-race-ethnicity"
  
  data = read_html(url)
  
  heading_table = data %>% 
    html_nodes("body") %>% 
    html_nodes("#page-wrapper") %>% 
    html_nodes("#page") %>% 
    html_nodes("#content-container") %>% 
    html_nodes("#main") %>% 
    html_nodes("article") %>% 
    html_nodes(".section") %>% 
    html_nodes(".region") %>% 
    html_nodes("#block-system-main") %>% 
    html_nodes(".content") %>% 
    html_nodes("#node-3210") %>% 
    html_nodes(".content") %>% 
    html_nodes(".field") %>% 
    html_nodes(".field-items") %>% 
    html_nodes(".field-item") %>% .[[1]] %>% 
    html_nodes("table") %>% 
    html_nodes("tbody") %>% 
    html_nodes("tr") %>% 
    html_nodes("td") %>% 
    map(., html_text) %>% 
    unlist() %>% 
    str_replace(",", "") %>% 
    as.numeric()
  
  demo_table = data %>% 
    html_nodes("body") %>% 
    html_nodes("#page-wrapper") %>% 
    html_nodes("#page") %>% 
    html_nodes("#content-container") %>% 
    html_nodes("#main") %>% 
    html_nodes("article") %>% 
    html_nodes(".section") %>% 
    html_nodes(".region") %>% 
    html_nodes("#block-system-main") %>% 
    html_nodes(".content") %>% 
    html_nodes("#node-3210") %>% 
    html_nodes(".content") %>% .[[1]] %>% 
    html_nodes(".paragraphs-items") %>% 
    html_nodes(".field") %>% 
    html_nodes(".field-items") %>% 
    html_nodes(".field-item") %>% 
    html_nodes("section") %>% .[[1]] %>% 
    html_nodes(".content") %>% .[[1]] %>% 
    html_nodes("div") %>% .[[8]] %>% 
    html_nodes("section") %>% 
    html_nodes("table") %>% 
    html_nodes("tbody") %>% 
    html_nodes("tr")
  
  nata = demo_table %>% .[[3]] %>% 
    html_nodes("td") %>% 
    map(., html_text) %>% 
    unlist() %>% 
    str_replace(",", "") %>% 
    as.numeric()
  
  asian = demo_table %>% .[[4]] %>% 
    html_nodes("td") %>% 
    map(., html_text) %>% 
    unlist() %>% 
    str_replace(",", "") %>% 
    as.numeric()
  
  afra = demo_table %>% .[[5]] %>% 
    html_nodes("td") %>% 
    map(., html_text) %>% 
    unlist() %>% 
    str_replace(",", "") %>% 
    as.numeric()
  
  white = demo_table %>% .[[7]] %>% 
    html_nodes("td") %>% 
    map(., html_text) %>% 
    unlist() %>% 
    str_replace(",", "") %>% 
    as.numeric()
  
  other = demo_table %>% .[[8]] %>% 
    html_nodes("td") %>% 
    map(., html_text) %>% 
    unlist() %>% 
    str_replace(",", "") %>% 
    as.numeric()
  
  not_unk = demo_table %>% .[[2]] %>% 
    html_nodes("td") %>% 
    map(., html_text) %>% 
    unlist() %>% 
    str_replace(",", "") %>% 
    as.numeric()
  
  hispanic = demo_table %>% .[[11]] %>% 
    html_nodes("td") %>% 
    map(., html_text) %>% 
    unlist() %>% 
    str_replace(",", "") %>% 
    as.numeric()
  
  non_hispanic = demo_table %>% .[[12]] %>% 
    html_nodes("td") %>% 
    map(., html_text) %>% 
    unlist() %>% 
    str_replace(",", "") %>% 
    as.numeric()
  
  eth_unk = demo_table %>% .[[10]] %>% 
    html_nodes("td") %>% 
    map(., html_text) %>% 
    unlist() %>% 
    str_replace(",", "") %>% 
    as.numeric()
  
  cases = heading_table[1]
  deaths = heading_table[2]
  
  skeleton[["tested"]][["total"]] = heading_table[3]
  skeleton[["deaths"]][["total"]] = deaths
  skeleton[["deaths"]][["race_NatA"]] = nata[4]
  skeleton[["deaths"]][["race_asian"]] = asian[4]
  skeleton[["deaths"]][["race_AfrA"]] = afra[4]
  skeleton[["deaths"]][["race_white"]] = white[4]
  skeleton[["deaths"]][["race_other"]] = other[4]
  skeleton[["deaths"]][["race_unk"]] = deaths - not_unk[4]
  skeleton[["deaths"]][["ethnicity_hispanic"]] = hispanic[4]
  skeleton[["deaths"]][["ethnicity_non_hispanic"]] = non_hispanic[4]
  skeleton[["deaths"]][["ethnicity_unk"]] = deaths = eth_unk[4]
  
  skeleton[["cases"]][["total"]] = cases
  skeleton[["cases"]][["race_NatA"]] = nata[2]
  skeleton[["cases"]][["race_asian"]] = asian[2]
  skeleton[["cases"]][["race_AfrA"]] = afra[2]
  skeleton[["cases"]][["race_white"]] = white[2]
  skeleton[["cases"]][["race_other"]] = other[2]
  skeleton[["cases"]][["race_unk"]] = cases - not_unk[2]
  skeleton[["cases"]][["ethnicity_hispanic"]] = hispanic[2]
  skeleton[["cases"]][["ethnicity_non_hispanic"]] = non_hispanic[2]
  skeleton[["cases"]][["ethnicity_unk"]] = cases - eth_unk[2]
  
  return(list(
    data = as_tibble(skeleton),
    comment = list(
      "Age data is only available in images, can't scrape"
    )
    ))
  
}
north_carolina = get_north_carolina()
```

# District of Columbia

```{r}
get_dc = function(date) {
  # Supply date in the form MonthName-Day-Year
  
  skeleton = skeleton_table()
  url = paste0(
    "https://coronavirus.dc.gov/sites/default/files/dc/sites/thrivebyfive/page_content/attachments/DC-COVID-19-Data-for-",
    date,
    ".xlsx")
  
  temp = tempfile(fileext = ".xlsx")
  download.file(url, destfile = temp, mode = 'wb')
  overall_stats = read_excel(temp, sheet = 1)
  case_by_race_ethnicity = read_excel(temp, sheet = 3)
  deaths_by_race = read_excel(temp, sheet = 4)
  
  # Log all the totals from this file
  today_stats = overall_stats[, ncol(overall_stats)] %>% unlist()
  
  skeleton[["tested"]][["total"]] = today_stats[2]
  skeleton[["cases"]][["total"]] = today_stats[3]
  skeleton[["deaths"]][["total"]] = today_stats[4]
  skeleton[["recovered"]][["total"]] = today_stats[5]
  
  # Log cases by race and ethnicity
  today_race_ethn = case_by_race_ethnicity[, ncol(case_by_race_ethnicity)] %>% 
    unlist
  skeleton[["cases"]][["race_unk"]] = today_race_ethn[3] + 
    today_race_ethn[10]
  skeleton[["cases"]][["race_white"]] = today_race_ethn[4]
  skeleton[["cases"]][["race_AfrA"]] = today_race_ethn[5]
  skeleton[["cases"]][["race_asian"]] = today_race_ethn[6]
  skeleton[["cases"]][["race_NatA"]] = today_race_ethn[7]
  skeleton[["cases"]][["race_other"]] = today_race_ethn[8] +
    today_race_ethn[9]
  skeleton[["cases"]][["ethnicity_unk"]] = today_race_ethn[12] +
    today_race_ethn[15]
  skeleton[["cases"]][["ethnicity_hispanic"]] = today_race_ethn[13]
  skeleton[["cases"]][["ethnicity_non_hispanic"]] = today_race_ethn[14]
    
  # Logging deaths
  today_deaths = deaths_by_race[, ncol(deaths_by_race)] %>% unlist()
  skeleton[["deaths"]][["race_asian"]] = today_deaths[3]
  skeleton[["deaths"]][["race_AfrA"]] = today_deaths[4]
  skeleton[["deaths"]][["ethnicity_hispanic"]] = today_deaths[5]
  skeleton[["deaths"]][["ethnicity_non_hispanic"]] = today_deaths[6]
  skeleton[["deaths"]][["race_unk"]] = today_deaths[7]
  
  return(list(
    data = as_tibble(skeleton),
    comments = list(
      "Deaths are combined between race and ethnicity"
    )
  ))
}

dc = get_dc("May-7-2020")
dc
```


# South Carolina

```{r}
get_south_carolina = function() {
  url = "https://scdhec.gov/infectious-diseases/viruses/coronavirus-disease-2019-covid-19/sc-testing-data-projections-covid-19"
  html = read_html(url) %>% 
    html_nodes("body") %>% 
    html_nodes("div") %>% .[[2]] %>% 
    html_nodes(".l-container--page") %>% 
    html_nodes("main") %>% 
    html_nodes("article .l-constrain") %>% .[[1]] %>% 
    html_nodes("div section") %>% .[[1]] %>% 
    html_nodes(".l-constrain .resize") %>% .[[1]] %>% 
    html_nodes("table") %>% 
    html_table() %>% .[[1]] %>% 
    pull(X2) %>% 
    str_replace(",", "") %>% 
    as.numeric()
  
  skeleton = skeleton_table()
  
  skeleton[["tested"]][["total"]] = html[7]
  skeleton[["negatives"]][["total"]] = html[3]
  skeleton[["cases"]][["total"]] = html[6]
    
  
  return(list(
    data = as_tibble(skeleton),
    comments = list(
      "Demographic and age data stored in complicated Tableau viz"
    )
  ))
}

south_carolina = get_south_carolina()
south_carolina
```

# New Jersey

```{r}
# Changing columns to account for provided data
nj_cols = c(
    "total",
    "age_0_4", 
    "age_5_17", 
    "age_18_29", 
    "age_30_49",
    "age_50_64", 
    "age_65_79", 
    "age_80+", 
    "age_unk",
    "sex_male", 
    "sex_female", 
    "sex_unk",
    "ethnicity_hispanic", 
    "ethnicity_non_hispanic",
    "ethnicity_unk",
    "race_white", 
    "race_AfrA",
    "race_NatA",
    "race_asian", 
    "race_other",
    "race_multi", 
    "race_unk")

get_new_jersey = function() {
  
  url = "https://www.nj.gov/health/cd/documents/topics/NCOV/COVID_Confirmed_Case_Summary.pdf"
  data = pdf_text(url) %>% .[1] %>% 
    str_split("\n") %>% .[[1]] %>% 
    str_squish()
  skeleton = skeleton_table(nj_cols)
  
  cases = data %>% .[9] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 5] %>% 
    as.numeric()
  
  deaths = data %>% .[12] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 6] %>% 
    as.numeric()
  
  hospitalizations = data %>% .[14] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 5] %>% 
    as.numeric()
  
  between_0_and_4 = data %>% .[17] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 4] %>% 
    as.numeric()
  
  between_5_and_17 = data %>% .[18] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 4] %>% 
    as.numeric()
  
  between_18_and_29 = data %>% .[19] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 4] %>% 
    as.numeric()
  
  between_30_and_49 = data %>% .[20] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 4] %>% 
    as.numeric()
  
  between_50_and_64 = data %>% .[21] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 4] %>% 
    as.numeric()
  
  between_65_and_79 = data %>% .[22] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 4] %>% 
    as.numeric()
  
  older_than_80 = data %>% .[23] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 2] %>% 
    as.numeric()
  
  male = data %>% .[29] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 2] %>% 
    as.numeric()
  
  female = data %>% .[28] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 2] %>% 
    as.numeric()
  
  unknown_sex = data %>% .[30] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 2] %>% 
    as.numeric()
  
  available_race = data %>% .[31] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 3] %>% 
    as.numeric()
  
  white = data %>% .[32] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 3] %>% 
    as.numeric()
  
  black = data %>% .[36] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 3] %>% 
    as.numeric()
  
  asian = data %>% .[37] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 3] %>% 
    as.numeric()
  
  other_race = data %>% .[38] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 3] %>% 
    as.numeric()
  
  hispanic = data %>% .[34] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 1] %>% 
    as.numeric()
  
  non_hispanic = (white + black + asian + other_race)
  
  unknown_ethnicity = cases - (hispanic + non_hispanic)
  
  unknown_race = cases - (non_hispanic)
  
  skeleton[["cases"]][["total"]] = cases
  skeleton[["cases"]][["sex_male"]] = male
  skeleton[["cases"]][["sex_female"]] = female
  skeleton[["cases"]][["sex_unk"]] = unknown_sex
  skeleton[["deaths"]][["total"]] = deaths
  
  skeleton[["cases"]][["age_0_4"]] = between_0_and_4
  skeleton[["cases"]][["age_5_17"]] = between_5_and_17
  skeleton[["cases"]][["age_18_29"]] = between_18_and_29
  skeleton[["cases"]][["age_30_49"]] = between_30_and_49
  skeleton[["cases"]][["age_50_64"]] = between_50_and_64
  skeleton[["cases"]][["age_65_79"]] = between_65_and_79
  skeleton[["cases"]][["age_80+"]] = older_than_80
  
  skeleton[["cases"]][["ethnicity_hispanic"]] = hispanic
  skeleton[["cases"]][["ethnicity_non_hispanic"]] = non_hispanic
  skeleton[["cases"]][["ethnicity_unk"]] = unknown_ethnicity
  
  skeleton[["cases"]][["race_white"]] = white
  skeleton[["cases"]][["race_AfrA"]] = black
  skeleton[["cases"]][["race_asian"]] = asian
  skeleton[["cases"]][["race_other"]] = other_race
  skeleton[["cases"]][["race_unk"]] = unknown_race
  
  return(list(
    data = as_tibble(skeleton),
    comments = list(
      "Site combined race and ethnicity, so calculation needed"
    )
  ))
}

new_jersey = get_new_jersey()
new_jersey
```

# New Hampshire

```{r}
current_week = "https://www.dhhs.nh.gov/dphs/cdcs/covid19/covid-weekly-report-05042020.pdf"

nh_cols = c(
    "total",
    "age_0_9", 
    "age_10_19",
    "age_20_29", 
    "age_30_39", 
    "age_40_49",
    "age_50_59", 
    "age_60_69", 
    "age_70_79", 
    "age_80+", 
    "age_unk",
    "sex_male", 
    "sex_female", 
    "sex_unk",
    "ethnicity_hispanic", 
    "ethnicity_non_hispanic",
    "ethnicity_unk",
    "race_white", 
    "race_AfrA",
    "race_NatA",
    "race_asian", 
    "race_other",
    "race_multi", 
    "race_unk")

get_new_hampshire = function(url) {
  first_page = pdf_text(url) %>% .[1] %>% 
    str_split("\n") %>% .[[1]] %>% 
    str_squish()
  second_page = pdf_text(url) %>% .[2] %>% 
    str_split("\n") %>% .[[1]] %>% 
    str_squish()
  skeleton = skeleton_table(nh_cols)
  
  cases = first_page %>% .[7] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 3] %>% 
    str_replace(",", "") %>% as.numeric()
  
  hospitalized = first_page %>% .[7] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 5] %>% 
    str_replace(",", "") %>% as.numeric()
  
  recovered = first_page %>% .[7] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 7] %>% 
    str_replace(",", "") %>% as.numeric()
  
  deaths = first_page %>% .[7] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 8] %>% 
    str_replace(",", "") %>% as.numeric()
  
  males = first_page %>% .[15] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 2] %>% 
    str_replace(",", "") %>% as.numeric()
  
  males_hosp = first_page %>% .[15] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 4] %>% 
    str_replace(",", "") %>% as.numeric()
  
  males_death = first_page %>% .[15] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 6] %>% 
    str_replace(",", "") %>% as.numeric()
  
  females = first_page %>% .[14] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 2] %>% 
    str_replace(",", "") %>% as.numeric()
  
  females_hosp = first_page %>% .[14] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 4] %>% 
    str_replace(",", "") %>% as.numeric()
  
  females_death = first_page %>% .[14] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 6] %>% 
    str_replace(",", "") %>% as.numeric()
  
  between_0_and_9 = first_page %>% .[17] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 2] %>% 
    str_replace(",", "") %>% as.numeric()
  
  between_0_and_9_hosp = first_page %>% .[17] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 4] %>% 
    str_replace(",", "") %>% as.numeric()
  
  between_0_and_9_death = first_page %>% .[17] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 6] %>% 
    str_replace(",", "") %>% as.numeric()
  
  between_10_and_19 = first_page %>% .[18] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 4] %>% 
    str_replace(",", "") %>% as.numeric()
  
  between_10_and_19_hosp = first_page %>% .[18] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 6] %>% 
    str_replace(",", "") %>% as.numeric()
  
  between_10_and_19_death = first_page %>% .[18] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 8] %>% 
    str_replace(",", "") %>% as.numeric()
  
  between_20_and_29 = first_page %>% .[19] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 4] %>% 
    str_replace(",", "") %>% as.numeric()
  
  between_20_and_29_hosp = first_page %>% .[19] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 6] %>% 
    str_replace(",", "") %>% as.numeric()
  
  between_20_and_29_death = first_page %>% .[19] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 8] %>% 
    str_replace(",", "") %>% as.numeric()
  
  between_30_and_39 = first_page %>% .[20] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 4] %>% 
    str_replace(",", "") %>% as.numeric()
  
  between_30_and_39_hosp = first_page %>% .[20] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 6] %>% 
    str_replace(",", "") %>% as.numeric()
  
  between_30_and_39_death = first_page %>% .[20] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 8] %>% 
    str_replace(",", "") %>% as.numeric()
  
  between_40_and_49 = first_page %>% .[21] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 4] %>% 
    str_replace(",", "") %>% as.numeric()
  
  between_40_and_49_hosp = first_page %>% .[21] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 6] %>% 
    str_replace(",", "") %>% as.numeric()
  
  between_40_and_49_death = first_page %>% .[21] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 8] %>% 
    str_replace(",", "") %>% as.numeric()
  
  between_50_and_59 = first_page %>% .[22] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 4] %>% 
    str_replace(",", "") %>% as.numeric()
  
  between_50_and_59_hosp = first_page %>% .[22] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 6] %>% 
    str_replace(",", "") %>% as.numeric()
  
  between_50_and_59_death = first_page %>% .[22] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 8] %>% 
    str_replace(",", "") %>% as.numeric()
  
  between_60_and_69 = first_page %>% .[23] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 4] %>% 
    str_replace(",", "") %>% as.numeric()
  
  between_60_and_69_hosp = first_page %>% .[23] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 6] %>% 
    str_replace(",", "") %>% as.numeric()
  
  between_60_and_69_death = first_page %>% .[23] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 8] %>% 
    str_replace(",", "") %>% as.numeric()
  
  between_70_and_79 = first_page %>% .[24] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 4] %>% 
    str_replace(",", "") %>% as.numeric()
  
  between_70_and_79_hosp = first_page %>% .[24] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 6] %>% 
    str_replace(",", "") %>% as.numeric()
  
  between_70_and_79_death = first_page %>% .[24] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 8] %>% 
    str_replace(",", "") %>% as.numeric()
  
  older_than_80 = first_page %>% .[25] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 3] %>% 
    str_replace(",", "") %>% as.numeric()
  
  older_than_80_hosp = first_page %>% .[25] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 5] %>% 
    str_replace(",", "") %>% as.numeric()
  
  older_than_80_death = first_page %>% .[25] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 7] %>% 
    str_replace(",", "") %>% as.numeric()
  
  has_race_ethn = second_page %>% .[12] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 1] %>% 
    str_replace(",", "") %>% as.numeric()
  
  has_race_ethn_hosp = second_page %>% .[12] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 2] %>% 
    str_replace(",", "") %>% as.numeric()
  
  has_race_ethn_death = second_page %>% .[12] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 3] %>% 
    str_replace(",", "") %>% as.numeric()
  
  white = second_page %>% .[6] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 2] %>% 
    str_replace(",", "") %>% as.numeric()
  
  white_hosp = second_page %>% .[6] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 4] %>% 
    str_replace(",", "") %>% as.numeric()
  
  white_death = second_page %>% .[6] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 6] %>% 
    str_replace(",", "") %>% as.numeric()
  
  black = second_page %>% .[8] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 5] %>% 
    str_replace(",", "") %>% as.numeric()
  
  black_hosp = second_page %>% .[8] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 7] %>% 
    str_replace(",", "") %>% as.numeric()
  
  black_death = second_page %>% .[8] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 9] %>% 
    str_replace(",", "") %>% as.numeric()
  
  other = second_page %>% .[9] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 2] %>% 
    str_replace(",", "") %>% as.numeric()
  
  other_hosp = second_page %>% .[9] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 4] %>% 
    str_replace(",", "") %>% as.numeric()
  
  other_death = second_page %>% .[9] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 6] %>% 
    str_replace(",", "") %>% as.numeric()
  
  asian = second_page %>% .[10] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 2] %>% 
    str_replace(",", "") %>% as.numeric()
  
  asian_hosp = second_page %>% .[10] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 4] %>% 
    str_replace(",", "") %>% as.numeric()
  
  asian_death = second_page %>% .[10] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 6] %>% 
    str_replace(",", "") %>% as.numeric()
  
  hispanic = second_page %>% .[7] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 2] %>% 
    str_replace(",", "") %>% as.numeric()
  
  hispanic_hosp = second_page %>% .[7] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 4] %>% 
    str_replace(",", "") %>% as.numeric()
  
  hispanic_death = second_page %>% .[7] %>% 
    str_split(" ", simplify = TRUE) %>% .[1, 6] %>% 
    str_replace(",", "") %>% as.numeric()
  
  non_hispanic = white + black + other + asian
  non_hispanic_hosp = white_hosp + black_hosp + other_hosp + asian_hosp
  non_hispanic_death = white_death + black_death + other_death + asian_death
  
  skeleton[["cases"]][["total"]] = cases
  skeleton[["cases"]][["sex_male"]] = males
  skeleton[["cases"]][["sex_female"]] = females
  
  skeleton[["cases"]][["age_0_9"]] = between_0_and_9
  skeleton[["cases"]][["age_10_19"]] = between_10_and_19
  skeleton[["cases"]][["age_20_29"]] = between_20_and_29
  skeleton[["cases"]][["age_30_39"]] = between_30_and_39
  skeleton[["cases"]][["age_40_49"]] = between_40_and_49
  skeleton[["cases"]][["age_50_59"]] = between_50_and_59
  skeleton[["cases"]][["age_60_69"]] = between_60_and_69
  skeleton[["cases"]][["age_70_79"]] = between_70_and_79
  skeleton[["cases"]][["age_80+"]] = older_than_80
  
  skeleton[["cases"]][["race_unk"]] = cases - has_race_ethn
  skeleton[["cases"]][["race_white"]] = white
  skeleton[["cases"]][["race_AfrA"]] = black
  skeleton[["cases"]][["race_other"]] = other
  skeleton[["cases"]][["race_asian"]] = asian
  
  skeleton[["cases"]][["ethnicity_hispanic"]] = hispanic
  skeleton[["cases"]][["ethnicity_non_hispanic"]] = non_hispanic
  
  skeleton[["hospitalized"]][["total"]] = hospitalized
  skeleton[["hospitalized"]][["sex_male"]] = males_hosp
  skeleton[["hospitalized"]][["sex_female"]] = females_hosp
  
  skeleton[["hospitalized"]][["age_0_9"]] = between_0_and_9_hosp
  skeleton[["hospitalized"]][["age_10_19"]] = between_10_and_19_hosp
  skeleton[["hospitalized"]][["age_20_29"]] = between_20_and_29_hosp
  skeleton[["hospitalized"]][["age_30_39"]] = between_30_and_39_hosp
  skeleton[["hospitalized"]][["age_40_49"]] = between_40_and_49_hosp
  skeleton[["hospitalized"]][["age_50_59"]] = between_50_and_59_hosp
  skeleton[["hospitalized"]][["age_60_69"]] = between_60_and_69_hosp
  skeleton[["hospitalized"]][["age_70_79"]] = between_70_and_79_hosp
  skeleton[["hospitalized"]][["age_80+"]] = older_than_80_hosp
  
  skeleton[["hospitalized"]][["race_unk"]] = hospitalized - has_race_ethn_hosp
  skeleton[["hospitalized"]][["race_white"]] = white_hosp
  skeleton[["hospitalized"]][["race_AfrA"]] = black_hosp
  skeleton[["hospitalized"]][["race_other"]] = other_hosp
  skeleton[["hospitalized"]][["race_asian"]] = asian_hosp
  
  skeleton[["hospitalized"]][["ethnicity_hispanic"]] = hispanic_hosp
  skeleton[["hospitalized"]][["ethnicity_non_hispanic"]] = non_hispanic_hosp
  
  skeleton[["deaths"]][["total"]] = deaths
  skeleton[["deaths"]][["sex_male"]] = males_death
  skeleton[["deaths"]][["sex_female"]] = females_death
  
  skeleton[["deaths"]][["age_0_9"]] = between_0_and_9_death
  skeleton[["deaths"]][["age_10_19"]] = between_10_and_19_death
  skeleton[["deaths"]][["age_20_29"]] = between_20_and_29_death
  skeleton[["deaths"]][["age_30_39"]] = between_30_and_39_death
  skeleton[["deaths"]][["age_40_49"]] = between_40_and_49_death
  skeleton[["deaths"]][["age_50_59"]] = between_50_and_59_death
  skeleton[["deaths"]][["age_60_69"]] = between_60_and_69_death
  skeleton[["deaths"]][["age_70_79"]] = between_70_and_79_death
  skeleton[["deaths"]][["age_80+"]] = older_than_80_death
  
  skeleton[["deaths"]][["race_unk"]] = cases - has_race_ethn
  skeleton[["deaths"]][["race_white"]] = white_death
  skeleton[["deaths"]][["race_AfrA"]] = black_death
  skeleton[["deaths"]][["race_other"]] = other_death
  skeleton[["deaths"]][["race_asian"]] = asian_death
  
  skeleton[["deaths"]][["ethnicity_hispanic"]] = hispanic_death
  skeleton[["deaths"]][["ethnicity_non_hispanic"]] = non_hispanic_death
  
  skeleton[["recovered"]][["total"]] = recovered
  
  return(list(
    data = as_tibble(skeleton),
    comment = list(
      "Race/ethnicity combined"
    )
  ))
}

new_hampshire = get_new_hampshire(current_week)
new_hampshire 
```

