---
title: "Comparing States"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(rvest)
library(httr)
library(plotly)
library(vistime)
```

```{r}
# read in case data
cases = read_csv("https://usafactsstatic.blob.core.windows.net/public/data/covid-19/covid_confirmed_usafacts.csv", col_names = TRUE) %>%
  janitor::clean_names() %>%
  pivot_longer(starts_with("x"),
               names_to = "date",
               values_to = "total_cases") %>%
  mutate(date = substr(date, 2, 8),
         date = str_replace_all(date, "_", "/"),
         date = as.Date(date, "%m/%d/%y")) %>%
  group_by(state, date) %>%
  summarize(total_cases = sum(total_cases)) %>%
  group_by(state) %>%
  mutate(new_cases = if_else(date != "2020-01-22", total_cases - lag(total_cases), total_cases))

# read in death data
deaths = read_csv("https://usafactsstatic.blob.core.windows.net/public/data/covid-19/covid_deaths_usafacts.csv", col_names = TRUE) %>%
  janitor::clean_names() %>%
  pivot_longer(starts_with("x"),
               names_to = "date",
               values_to = "total_deaths") %>%
  mutate(date = substr(date, 2, 8),
         date = str_replace_all(date, "_", "/"),
         date = as.Date(date, "%m/%d/%y")) %>%
  group_by(state, date) %>%
  summarize(total_deaths = sum(total_deaths)) %>%
  group_by(state) %>%
  mutate(new_deaths = if_else(date != "2020-01-22", total_deaths - lag(total_deaths), total_deaths)) 

# read in pop data
pop = read_csv("https://usafactsstatic.blob.core.windows.net/public/data/covid-19/covid_county_population_usafacts.csv", col_names = TRUE) %>%
  janitor::clean_names() %>%
  group_by(state) %>%
  summarize(population = sum(population))

# join population counts to cases and deaths datasets for normalized counts
cases2 = left_join(cases, pop, by = "state") %>%
  mutate(new_cases_norm = (new_cases/population)*100000) %>%
  select(state, date, new_cases, new_cases_norm) %>%
  pivot_longer(new_cases:new_cases_norm,
               names_to = "num_type",
               values_to = "val") %>%
  mutate(num_type = if_else(num_type == "new_cases", "Count", "Per 100k")) %>%
  arrange(state, num_type, date) %>%
  mutate(roll_avg3 = (val + lag(val) + lead(val))/3,
         roll_avg5 = (val + lag(val) + lead(val) + lag(lag(val)) + lead(lead(val)))/5,
         roll_avg7 = (val + lag(val) + lead(val) + lag(lag(val)) + lead(lead(val)) + lag(lag(lag(val))) + lead(lead(lead(val))))/7) %>%
  mutate(roll_avg3 = ifelse(num_type != lag(num_type) | num_type != lead(num_type), NA, roll_avg3),
         roll_avg5 = ifelse(num_type != lag(num_type) | num_type != lead(num_type) | num_type != lag(lag(num_type)) | num_type != lead(lead(num_type)), NA, roll_avg5),
         roll_avg7 = ifelse(num_type != lag(num_type) | num_type != lead(num_type) | num_type != lag(lag(num_type)) | num_type != lead(lead(num_type)) | num_type != lag(lag(lag(num_type))) | num_type != lead(lead(lead(num_type))), NA, roll_avg7)) %>%
  pivot_longer(roll_avg3:roll_avg7, 
               names_to = "roll_avg_num",
               values_to = "roll_avg_val") %>%
  mutate(roll_avg_num = substring(roll_avg_num, 9))


deaths2 = left_join(deaths, pop, by = "state") %>%
  mutate(new_deaths_norm = (new_deaths/population)*100000) %>%
  select(state, date, new_deaths, new_deaths_norm) %>%
  pivot_longer(new_deaths:new_deaths_norm,
               names_to = "num_type",
               values_to = "val") %>%
  mutate(num_type = if_else(num_type == "new_deaths", "Count", "Per 100k")) %>%
  arrange(state, num_type, date) %>%
  mutate(roll_avg3 = (val + lag(val) + lead(val))/3,
         roll_avg5 = (val + lag(val) + lead(val) + lag(lag(val)) + lead(lead(val)))/5,
         roll_avg7 = (val + lag(val) + lead(val) + lag(lag(val)) + lead(lead(val)) + lag(lag(lag(val))) + lead(lead(lead(val))))/7) %>%
  mutate(roll_avg3 = ifelse(num_type != lag(num_type) | num_type != lead(num_type), NA, roll_avg3),
         roll_avg5 = ifelse(num_type != lag(num_type) | num_type != lead(num_type) | num_type != lag(lag(num_type)) | num_type != lead(lead(num_type)), NA, roll_avg5),
         roll_avg7 = ifelse(num_type != lag(num_type) | num_type != lead(num_type) | num_type != lag(lag(num_type)) | num_type != lead(lead(num_type)) | num_type != lag(lag(lag(num_type))) | num_type != lead(lead(lead(num_type))), NA, roll_avg7)) %>%
  pivot_longer(roll_avg3:roll_avg7, 
               names_to = "roll_avg_num",
               values_to = "roll_avg_val") %>%
  mutate(roll_avg_num = substring(roll_avg_num, 9))
```

Column {.sidebar}
-----------------------------------------------------------------------
```{r}
radioButtons(
  "count_choice",
  label = h3("Select Count Type"),
  choices = c("Count", "Per 100k"), selected = "Count"
)
```

```{r}
radioButtons(
  "roll_choice",
  label = h3("Select Rolling Average"),
  choices = c("3", "5", "7"), selected = "3"
)
```


```{r}
states = cases2 %>% distinct(state) %>% pull()

selectInput(
  "state_choice1",
  label = h3("Select First State"),
  choices = states, selected = "AK"
)
```

```{r}
states = cases2 %>% distinct(state) %>% pull()

selectInput(
  "state_choice2",
  label = h3("Select Second State"),
  choices = states, selected = "AL"
)
```

```{r}
states = cases2 %>% distinct(state) %>% pull()

selectInput(
  "state_choice3",
  label = h3("Select Third State"),
  choices = states, selected = "AR"
)
```

```{r}
states = cases2 %>% distinct(state) %>% pull()

selectInput(
  "state_choice4",
  label = h3("Select Fourth State"),
  choices = states, selected = "AZ"
)
```

```{r}
states = cases2 %>% distinct(state) %>% pull()

selectInput(
  "state_choice5",
  label = h3("Select Fifth State"),
  choices = states, selected = "CA"
)
```
   
*Note: There may be artificial spikes or negative values from changes in recording and classification of COVID-19 data. For example, some spikes are caused by the inclusion of probable death counts.*    

Column {data-width=500}
-----------------------------------------------------------------------

### Rolling Average of COVID-19 Cases by Day and State

```{r}
renderPlotly({
 cases2 %>%
    filter(state %in% c(input$state_choice1, input$state_choice2,
                        input$state_choice3, input$state_choice4, input$state_choice5),
           num_type == input$count_choice,
           roll_avg_num == input$roll_choice,
           date >= min(date[val != 0])) %>%
    plot_ly(
      x = ~date, y = ~roll_avg_val, color = ~state, 
      type = "scatter", mode = "lines",
      hoverinfo = "text",
      text = ~paste0("State: ", state, "\nDate: ", date, '\nRolling Avg: ', prettyNum(round(roll_avg_val, 2), big.mark = ",")),
      colors = c("#71B2C9", "#FF9800", "#AE2573", "#D14124", "#B7BF10")
    ) %>%
    layout(
      xaxis = list(title = "Date"),
      yaxis = list(title = "New COVID-19 Cases")
    )
})
```

Column {data-width=500}
-----------------------------------------------------------------------

### Rolling Average of COVID-19 Deaths by Day and State

```{r}
renderPlotly({
 deaths2 %>%
    filter(state %in% c(input$state_choice1, input$state_choice2,
                        input$state_choice3, input$state_choice4, input$state_choice5),
           num_type == input$count_choice,
           roll_avg_num == input$roll_choice,
           date >= min(date[val != 0])) %>%
    plot_ly(
      x = ~date, y = ~roll_avg_val, color = ~state, 
      type = "scatter", mode = "lines",
      hoverinfo = "text",
      text = ~paste0("State: ", state, "\nDate: ", date, '\nRolling Avg: ', prettyNum(round(roll_avg_val, 2), big.mark = ",")),
      colors = c("#71B2C9", "#FF9800", "#AE2573", "#D14124", "#B7BF10")
    ) %>%
    layout(
      xaxis = list(title = "Date"),
      yaxis = list(title = "New COVID-19 Deaths")
    )
})
```


