---
title: "Courtney Manual Scraping Workflow"
---

```{r}
# Step 1: Load in my R source files
library(tidyverse)
library(pdftools)
library(rvest)
library(lubridate)
library(readxl)
source("./source/states.R")
source("./source/states_constants.R")
```

```{r}
# Step 2: Do the data entry 
hawaii = get_hawaii() # Courtney
# error at the end: skeleton[["tested"]][["total"]] : subscript out of bounds


idaho = get_idaho() # Courtney

# at total tested entry: "error in skeleton [["tested"]][["total"]] subscript out of bounds"
```

```{r}
# Step 3: combine the two states together with bind_rows
# Name your variable like manual_data_yearmonthday_initials
# ie: manual_data_20200519_cbp = bind_rows(arizona, kansas, iowa)

manual_data_20200523_cej = bind_rows(hawaii, idaho)
```

```{r}
# Step 4: save your data as an Rda with a similar name
# ie: save(manual_data_20200519_cbp, file = "manual_data_20200519_cbp.rda")

save(manual_data_20200523_cej, file = "manual_data_20200523_cej.rda")

# Then place into the Sharepoint! 
# As Aijin suggested, try doing this at least one day a week, like Friday
# Thanks everyone for helping out
```

