---
title: "Scraping"
author: "Courtney Johnson"
date: "May 4, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(httr)
library(rvest)
library(pdftools)
library(glue)
```


### Wyoming

```{r, scrape}
# url = "https://health.wyo.gov/publichealth/infectious-disease-epidemiology-unit/disease/novel-coronavirus/covid-19-map-and-statistics/"

# wy_xml = read_html(url) %>%
#   html_nodes('center') %>%
#   html_table(fill = TRUE, header = TRUE)
```


### New Hampshire

```{r, nh_scrape}
#  "05042020"

# scraping function which only needs to take in the date of the report
nh_scrape_fun = function(date){
  
  # put the date into url and create a way to automatically run things with different dates
url = "https://www.dhhs.nh.gov/dphs/cdcs/covid19/covid-weekly-report-{date}.pdf"
url = glue(url)

# read in text
nh_text = pdf_text(url) %>%
  readr::read_lines()

# save text for first table
outcome_table = nh_text[4:7] %>%
  str_replace_all(",", "") %>%
  str_replace("Intensive Care Unit", "ICU") %>%
  str_squish() %>%
  strsplit(split = " ") 

# add recovered and deaths labels to the existing row with labels
outcome_table[[3]][8:9] = outcome_table[[2]][1:2]

# save values and column names
outcome_table = outcome_table[3:4]


# make dataframe and add variable names; only keep necessary information
outcomes = outcome_table[2] %>%
  plyr::ldply() %>%
  rename(level = V1, current_inf = V2, total_case = V3, current_hosp = V4,
         total_hosp = V5, current_icu = V6, total_icu = V7, 
         recovered = V8, total_death = V9) %>%
  mutate(level = "total") %>%
  select(level, total_case, total_hosp, total_icu, recovered, total_death)
  

# save text for first demographic table
demo1 = nh_text[9:25] %>%
  str_replace_all("% of Total", "Total_Perc") %>%
  str_replace("SUMMARY OF PERSONS WITH COVID-19", "Characteristic") %>%
  str_replace("Healthcare Workers", "Healthcare_workers") %>%
  str_replace("Age Group \\(in years\\)", "Age_grp") %>%
  str_replace_all(" - ", "_") %>%
  str_replace("-", "_") %>%
  str_replace(",", "") %>%
  str_replace(" \\+", "_") %>%
  str_squish() %>%
  strsplit(split = " ")

# combine variable names
demo1[[2]][2:7] = demo1[[3]][1:6]

# save values and create data frames
# sex
sex_demo = demo1[6:7] %>%
  plyr::ldply() %>%
  rename(level = V1, positive_gender = V2, percent_of_total_inf = V3,
         hosp_gender = V4, percent_of_total_hosp = V5, death_gender = V6, 
         percent_of_total_deaths = V7) %>%
  mutate(level = if_else(level == "Male", "sex_male", "sex_female")) %>%
  select(level, positive_gender, hosp_gender, death_gender)

# age group
age_demo = demo1[9:17] %>%
  plyr::ldply() %>%
  rename(level = V1, positive_age = V2, percent_of_total_inf = V3,
         hosp_age = V4, percent_of_total_hosp = V5, death_age = V6, 
         percent_of_total_deaths = V7) %>%
  mutate(level = str_c("age_", level)) %>%
  select(level, positive_age, hosp_age, death_age)

# healthcare workers
healthcare_demo = demo1[4] %>%
  plyr::ldply() %>%
  rename(level = V1, comment_case = V2, percent_of_total_inf = V3,
         comment_hosp = V4, percent_of_total_hosp = V5, comment_death = V6, 
         percent_of_total_deaths = V7) %>%
  select(level, comment_case, comment_hosp, comment_death)

 
# save text for second demographic table (race/eth)
demo2 = nh_text[36:43] %>%
  str_replace_all("% of Total", "Total_Perc") %>%
  str_replace("Race/Ethnicity", "Race_Eth") %>%
  str_replace("White2", "race_eth_white") %>%
  str_replace("Hispanic/Latino1", "race_eth_hispanic") %>%
  str_replace("Black or African American2", "race_eth_black") %>%
  str_replace("Other3", "race_eth_other") %>%
  str_replace("Asian2", "race_eth_asian") %>%
  str_replace("Percent of NH", "Perc_NH") %>%
  str_replace(",", "") %>%
  str_squish() %>%
  strsplit(split = " ")

# keep values
race_eth_demo = demo2[4:8] %>%
  plyr::ldply() %>%
  rename(level = V1, positive_race = V2, percent_of_total_inf = V3, 
         hosp_race = V4, percent_of_total_hosp = V5, death_race = V6, 
         percent_of_total_deaths = V7, percent_of_NH_pop = V8) %>%
  select(level, positive_race, hosp_race, death_race)

# modify race/eth to show total with collected info
# race_eth_demo = race_eth_demo %>%
#   mutate(percent_of_total_inf = paste(percent_of_total_inf, "/1525"),
#          percent_of_total_hosp = paste(percent_of_total_hosp, "/211"),
#          percent_of_total_deaths = paste(percent_of_total_deaths, "/40"))

# combine into one table
plyr::rbind.fill(outcomes, sex_demo, age_demo, race_eth_demo, healthcare_demo) %>%
  select(level, total_case, positive_race, positive_age, positive_gender,
         total_death, death_race, death_age, death_gender, total_hosp,
         hosp_race, hosp_age, hosp_gender, total_icu, recovered, comment_case,
         comment_hosp, comment_death)
  
}

```

### Run function for different dates
```{r}
nh_04272020 = nh_scrape_fun(date = "04272020")
nh_05042020 = nh_scrape_fun(date = "05042020")
```


### Kansas

```{r, ks_scrape}
# must redownload pdf and add date to end of pdf name 

ks_scrape_fun = function(ks_date){
  
  # to run without knitting, use single ., to run with knitting, use double ..
# issue with how i originally made the file?
location = "../pdfs/KS COVID-19 Outbreak Summary{ks_date}.pdf"
location = glue(location)

ks_text = pdf_text(location) %>%
  readr::read_lines()


# get total cases, total hosp, total deaths from first few rows
ks_total = ks_text[1:16] %>%
  str_replace_all(",", "") %>%
  str_replace_all("\\*", "") %>%
  str_squish() %>%
  strsplit(split = " ") 

# make data frame of total level stats
ks_tot = tibble(level = "total",
       total_case = ks_total[[3]],
       total_hosp = ks_total[[9]],
       total_death = ks_total[[16]],
       positivity_rate = str_c(ks_text[226], " per 1000"),
       positivity_percent = ks_text[741],
       total_tested = str_replace_all(ks_text[731], ",", "")) 

# data for age case demographics
ks_case_age = ks_text[393:404] %>%
  str_replace_all(",", "") %>%
  str_replace_all("years", "") %>%
  str_replace("Not Reported", "not_reported") %>%
  str_replace("Total", "total") %>%
  str_squish() %>%
  strsplit(split = " ") %>%
  plyr::ldply() %>%
  rename(level = V1, positive_age = V2) %>%
  select(level, positive_age) %>%
  mutate(level = str_c("age_", level))

# data for sex case demographics
ks_case_sex = ks_text[408:411] %>%
  str_replace_all(",", "") %>%
  str_to_lower() %>%
  str_replace("not reported/unknown", "not_reported") %>%
  str_squish() %>%
  strsplit(split = " ") %>%
  plyr::ldply() %>%
  rename(level = V1, positive_gender = V2) %>%
  mutate(level = str_c("sex_", level)) %>%
  select(level, positive_gender)

# case race demographics
ks_race = ks_text[415:420] %>%
  str_replace_all(",", "") %>%
  str_to_lower() %>%
  str_replace("or african american", "") %>%
  str_replace("american indian or alaska nat..", "american_indian_alaskan_native") %>%
  str_replace("other race", "other") %>%
  str_replace("not reported/missing", "not_reported") %>%
  str_squish() %>%
  strsplit(split = " ") 

# add na to last row in order to allow table format
ks_race[[6]][3] = "na"

# create table
ks_case_race = ks_race %>%
  plyr::ldply() %>%
  rename(level = V1, positive_race = V2) %>%
  mutate(level = str_c("race_", level)) %>%
  select(level, positive_race)

# case ethnicity demographics
ks_eth = ks_text[425:427] %>%
  str_to_lower() %>%
  str_replace_all(",", "") %>%
  str_replace_all("/latino", "") %>%
  str_replace("not ", "non_") %>%
  str_replace(" or missing", "") %>%
  str_squish() %>%
  strsplit(split = " ")

# add na so can make table
ks_eth[[3]][3] = "na"

ks_case_eth = ks_eth %>%
  plyr::ldply() %>%
  rename(level = V1, positive_race = V2) %>%
  mutate(level = str_c("eth_", level)) %>%
  select(level, positive_race)

# hosp age demo
ks_hosp_age = ks_text[545:554] %>%
  str_replace_all(" years", "") %>%
  str_replace_all(",", "") %>%
  str_to_lower() %>%
  str_squish() %>%
  strsplit(split = " ") %>%
  plyr::ldply() %>%
  rename(level = V1, hosp_age = V2) %>%
  mutate(level = str_c("age_", level)) %>%
  select(level, hosp_age)


# hosp race demo
ks_hosp_race = ks_text[558:564] %>%
  str_to_lower() %>%
  str_replace_all(",", "") %>%
  str_replace("or african american", "") %>%
  str_replace("american indian or alaska na..", "american_indian_alaskan_native") %>%
  str_replace("other race", "other") %>%
  str_replace("not reported/missing", "not_reported") %>%
  str_squish() %>%
  strsplit(split = " ") %>%
  plyr::ldply() %>%
  rename(level = V1, hosp_race = V2) %>%
  mutate(level = str_c("race_", level)) %>%
  select(level, hosp_race)

# hosp eth demo
ks_hosp_eth = ks_text[568:571] %>%
  str_to_lower() %>%
  str_replace_all(",", "") %>%
  str_replace_all(" or latino", "") %>%
  str_replace(" or missing", "") %>%
  str_replace("not hispanic", "non_hispanic") %>%
  str_squish() %>%
  strsplit(split = " ") %>%
  plyr::ldply() %>%
  rename(level = V1, hosp_race = V2) %>%
  mutate(level = str_c("eth_", level)) %>%
  select(level, hosp_race) 

# death race demo
ks_d_race = ks_text[657:661] %>%
  str_to_lower() %>%
  str_replace_all(",", "") %>%
  str_replace(" or african american", "") %>%
  str_replace(" indian or alaska na..", "_indian_alaskan_native") %>%
  str_replace(" reported/missing", "_reported") %>%
  str_replace("other race", "other") %>%
  str_squish() %>% 
  strsplit(split = " ") 

# add na to not reported to allow for table
ks_d_race[[4]][3] = "na"

# make into table
ks_death_race = ks_d_race %>%
  plyr::ldply() %>%
  rename(level = V1, death_race = V2) %>%
  mutate(level = str_c("race_", level)) %>%
  select(level, death_race)

# death eth demo
ks_d_eth = ks_text[665:667] %>%
  str_to_lower() %>%
  str_replace_all(",", "") %>%
  str_replace_all(" or latino", "") %>%
  str_replace("not hispanic", "non_hispanic") %>%
  str_replace("not reported/missing", "not_reported") %>%
  str_squish() %>%
  strsplit(split = " ")

# add na to allow table to be made
ks_d_eth[[3]][3] = "na"

# make table
ks_death_eth = ks_d_eth %>%
  plyr::ldply() %>%
  rename(level = V1, death_race = V2) %>%
  mutate(level = str_c("eth_", level)) %>%
  select(level, death_race)

# death age demo- might have to update this if people younger than 35 die
ks_death_age = ks_text[687:693] %>%
  str_to_lower() %>%
  str_replace_all(",", "") %>%
  str_replace_all(" years", "") %>%
  str_squish() %>%
  strsplit(split = " ") %>%
  plyr::ldply() %>%
  rename(level = V1, death_age = V2) %>%
  mutate(level = str_c("age_", level)) %>%
  select(level, death_age)

# death sex demo
ks_death_sex = ks_text[697:699] %>%
  str_to_lower() %>%
  str_replace_all(",", "") %>%
  str_squish() %>%
  strsplit(split = " ") %>%
  plyr::ldply() %>%
  rename(level = V1, death_gender = V2) %>%
  mutate(level = str_c("sex_", level)) %>%
  select(level, death_gender)

# combine all tables into outcome table
plyr::rbind.fill(ks_tot, ks_case_race, ks_case_eth, ks_case_age, ks_case_sex,
                 ks_death_race, ks_death_eth, ks_death_age, ks_death_sex,
                 ks_hosp_race, ks_hosp_eth, ks_hosp_age) %>%
  select(level, total_tested, total_case, positive_race, positive_age, 
         positive_gender, positivity_rate, positivity_percent, total_death,
         death_race, death_age, death_gender, total_hosp, hosp_race, hosp_age)
  
}

```

### Kansas Tables
```{r, ks_tables}
# run function with date
ks_05102020 = ks_scrape_fun(ks_date = "05102020")
```


### Idaho
```{r, idaho}
# so far, it looks like the most difficult but accurate way is to download the crosstab data from the dashboard (sex, age, race, ethnicity, total) for both cases and deaths separately
# this would mean downloading 10 csv files each day manually-there isn't a file location link that I can find that would enable me to loop through automatically downloading each file
# I also manually changed the filenames to the format below so that they would make more sense when being read in


date = "05082020"

# age file is formatted differently
type = c("Eth", "Race", "Sex", "Total")

file_name = "../Data/ID_Case{type}_{date}.csv"

file_loc = glue(file_name)

df = map(.x = file_loc, ~read.csv(.x, header = TRUE, sep = "\t", 
                             fileEncoding = "UTF-16LE")) 


read.csv("../Data/ID_CaseAge_05082020.csv", header = FALSE, sep = "",
         fileEncoding = "UTF-16LE")
```

### South Dakota
```{r, sd}
url = "https://doh.sd.gov/news/coronavirus.aspx#SD"

sd_xml = read_html(url)

# this doesn't work, because it doesn't pick up the table on the dashboard
# tabs = sd_xml %>%
#   html_nodes('table') %>%
#   html_table(fill = TRUE, header = TRUE)
```

